const API_URL = 'https://script.google.com/macros/s/AKfycbw84pPMgzFGDAr_ZG5d3x4C9zcfe9y2AHNdKNp6w8Almsk78Tx47HzSIKmSGjoatmT0/exec';
const POSTS_KEY = 'blog_posts';
const TOKEN_KEY = 'blog_auth_token';
const nav = document.querySelector('.site-nav');
const menu = document.querySelector('.menu-toggle');
if (menu && nav) menu.addEventListener('click', () => { const open = nav.classList.toggle('is-open'); menu.setAttribute('aria-expanded', String(open)); });
function readPosts() { try { return JSON.parse(localStorage.getItem(POSTS_KEY) || '[]'); } catch { return []; } }
function savePosts(posts) { localStorage.setItem(POSTS_KEY, JSON.stringify(posts)); }
async function postApi(payload) { const result = await callAuthApi(payload); if (!result.ok) throw new Error(result.message || '게시글 요청에 실패했습니다.'); return result; }
function cachedPosts() { return readPosts(); }
async function syncPosts() { if (!localStorage.getItem(TOKEN_KEY)) return cachedPosts(); try { const result = await postApi({ action: 'post_list' }); const posts = result.posts.map(post => ({ ...post, date: post.createdAt })); savePosts(posts); return posts; } catch { return cachedPosts(); } }
function newId() { return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; }
function formatDate(value) { return new Date(value).toLocaleDateString('ko-KR').replaceAll('. ', '.').replace(/\.$/, ''); }
function showMessage(form, message, error = false) { const target = form.querySelector('.form-message'); if (target) { target.textContent = message; target.style.color = error ? '#c0392b' : ''; } }
async function callAuthApi(payload) { const response = await fetch(API_URL, { method: 'POST', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify(payload) }); return response.json(); }
function clearAuth() { localStorage.removeItem(TOKEN_KEY); localStorage.removeItem('blog_user'); }
function setupAuthNavigation() {
  if (!nav) return; const login = nav.querySelector('a[href="login.html"]'); const write = nav.querySelector('a[href="write.html"]');
  if (localStorage.getItem(TOKEN_KEY)) { if (login) { login.textContent = '로그아웃'; login.href = '#logout'; login.addEventListener('click', async e => { e.preventDefault(); try { await callAuthApi({ action: 'logout', token: localStorage.getItem(TOKEN_KEY) }); } finally { clearAuth(); location.href = 'index.html'; } }); } const profile = nav.querySelector('a[href="profile.html"]'); if (profile) profile.dataset.profileLink = 'true'; else { const link = document.createElement('a'); link.href = 'profile.html'; link.dataset.profileLink = 'true'; link.textContent = '프로필'; nav.insertBefore(link, login || write); } }
  else if (login && !nav.querySelector('[data-signup-link]')) { const link = document.createElement('a'); link.href = 'signup.html'; link.dataset.signupLink = 'true'; link.textContent = '회원가입'; nav.insertBefore(link, write); }
}
function setupAuthForm() {
  const form = document.querySelector('.auth-card form'); if (!form) return; const isSignup = location.pathname.endsWith('signup.html');
  form.addEventListener('submit', async e => { e.preventDefault(); const fields = new FormData(form); const payload = { action: isSignup ? 'signup' : 'login', email: fields.get('email'), password: fields.get('password') }; if (isSignup) payload.name = fields.get('name'); const button = form.querySelector('button[type="submit"]'); if (button) button.disabled = true; showMessage(form, '처리 중입니다...'); try { const result = await callAuthApi(payload); if (!result.ok) return showMessage(form, result.message || '요청을 처리하지 못했습니다.', true); localStorage.setItem(TOKEN_KEY, result.token); localStorage.setItem('blog_user', JSON.stringify(result.user)); showMessage(form, result.message || '완료되었습니다.'); setTimeout(() => { location.href = 'profile.html'; }, 400); } catch { showMessage(form, '서버에 연결할 수 없습니다. 잠시 후 다시 시도하세요.', true); } finally { if (button) button.disabled = false; } });
}
function postLink(post) { return `post-detail.html?id=${encodeURIComponent(post.id)}`; }
function renderPostCard(post) { const article = document.createElement('article'); article.className = 'post-card'; article.innerHTML = `<p class="post-meta"></p><h3><a></a></h3><p class="post-excerpt"></p><a class="text-link">자세히 읽기 →</a>`; article.querySelector('.post-meta').textContent = `${post.category} · ${formatDate(post.date)}`; article.querySelector('h3 a').textContent = post.title; article.querySelector('h3 a').href = postLink(post); article.querySelector('.post-excerpt').textContent = post.content; article.querySelector('.text-link').href = postLink(post); return article; }
function renderListItem(post, editable = false) { const item = document.createElement('article'); item.className = 'list-post user-post'; item.innerHTML = `<div class="list-date"></div><div><h2><a></a></h2><p></p><a class="text-link" href="${postLink(post)}">자세히 읽기 →</a><div class="post-actions"></div></div>`; item.querySelector('.list-date').textContent = `${formatDate(post.date)}\n${post.category}`; item.querySelector('.list-date').style.whiteSpace = 'pre-line'; item.querySelector('h2 a').textContent = post.title; item.querySelector('p').textContent = post.content; if (editable) { const actions = item.querySelector('.post-actions'); const edit = document.createElement('a'); edit.className = 'text-link'; edit.href = `write.html?edit=${encodeURIComponent(post.id)}`; edit.textContent = '수정'; const del = document.createElement('button'); del.type = 'button'; del.className = 'post-delete'; del.textContent = '삭제'; del.onclick = async () => { if (!confirm('이 글을 삭제할까요?')) return; try { if (localStorage.getItem(TOKEN_KEY)) await postApi({ action: 'post_delete', token: localStorage.getItem(TOKEN_KEY), id: post.id }); else savePosts(readPosts().filter(p => p.id !== post.id)); item.remove(); } catch (error) { alert(error.message); } }; actions.append(edit, del); } return item; }
function drawHome(grid, posts) { if (posts.length) { grid.replaceChildren(); posts.slice(0, 3).forEach(post => grid.appendChild(renderPostCard(post))); } else grid.innerHTML = '<p class="empty-state">아직 등록된 게시글이 없습니다.</p>'; }
function setupHomePosts() { const grid = document.querySelector('#latest-posts'); if (!grid) return; drawHome(grid, cachedPosts()); syncPosts().then(posts => drawHome(grid, posts)); }
function drawList(list, posts) { list.replaceChildren(); posts.forEach(post => list.appendChild(renderListItem(post))); if (!posts.length) list.innerHTML = '<p class="empty-state">아직 등록된 게시글이 없습니다.</p>'; }
function setupPostList() { const list = document.querySelector('#post-list'); if (!list) return; drawList(list, cachedPosts()); syncPosts().then(posts => drawList(list, posts)); }
function drawProfile(list, posts) { list.replaceChildren(); posts.forEach(post => list.appendChild(renderListItem(post, true))); if (!posts.length) list.innerHTML = '<p class="empty-state">아직 작성한 게시글이 없습니다.</p>'; const count = document.querySelector('.stats b'); if (count) count.textContent = posts.length; }
function setupProfilePosts() { const section = document.querySelector('.profile-posts'); const list = section?.querySelector('.post-list'); if (!list) return; drawProfile(list, cachedPosts()); syncPosts().then(posts => drawProfile(list, posts)); }
function setupWriteForm() { const form = document.querySelector('.editor-wrap form'); if (!form) return; const category = form.querySelector('[name="category"]'); const title = form.querySelector('[name="title"]'); const content = form.querySelector('[name="content"]'); const editId = new URLSearchParams(location.search).get('edit'); const existing = editId && readPosts().find(p => p.id === editId); const draftKey = `blog_draft_${editId || 'new'}`; const draft = !existing && JSON.parse(localStorage.getItem(draftKey) || 'null'); if (existing) { title.value = existing.title; content.value = existing.content; category.value = existing.category; const heading = document.querySelector('.form-card h1'); if (heading) heading.textContent = '글 수정'; } else if (draft) { title.value = draft.title || ''; content.value = draft.content || ''; category.value = draft.category || category.value; }
  let draftTimer; [category, title, content].forEach(field => field.addEventListener('input', () => { clearTimeout(draftTimer); draftTimer = setTimeout(() => localStorage.setItem(draftKey, JSON.stringify({ title: title.value, content: content.value, category: category.value, savedAt: Date.now() })), 250); }));
  form.addEventListener('submit', async e => { e.preventDefault(); const titleValue = title.value.trim(); const contentValue = content.value.trim(); if (!titleValue || !contentValue) return showMessage(form, '제목과 내용을 입력해 주세요.', true); try { if (localStorage.getItem(TOKEN_KEY)) { await postApi(existing ? { action: 'post_update', token: localStorage.getItem(TOKEN_KEY), id: editId, title: titleValue, content: contentValue, category: category.value } : { action: 'post_create', token: localStorage.getItem(TOKEN_KEY), title: titleValue, content: contentValue, category: category.value }); } else { const posts = readPosts(); if (existing) { const index = posts.findIndex(p => p.id === editId); posts[index] = { ...posts[index], title: titleValue, content: contentValue, category: category.value, updatedAt: new Date().toISOString() }; } else posts.unshift({ id: newId(), title: titleValue, content: contentValue, category: category.value, date: new Date().toISOString() }); savePosts(posts); } showMessage(form, existing ? '게시글을 수정했습니다.' : '게시글을 발행했습니다.'); setTimeout(() => { location.href = 'profile.html'; }, 400); } catch (error) { showMessage(form, error.message, true); } });
  const previewButton = form.querySelector('.secondary-btn'); const preview = document.querySelector('.post-preview'); if (previewButton && preview) previewButton.addEventListener('click', () => { if (!title.value.trim() || !content.value.trim()) return showMessage(form, '제목과 내용을 입력한 뒤 미리보기를 눌러 주세요.', true); preview.querySelector('.post-preview-meta').textContent = `${category.value} · 미리보기`; preview.querySelector('.post-preview-title').textContent = title.value.trim(); preview.querySelector('.post-preview-content').textContent = content.value.trim(); preview.hidden = false; preview.scrollIntoView({ behavior: 'smooth' }); });
}
function setupDetail() { const article = document.querySelector('.article'); if (!article) return; const id = new URLSearchParams(location.search).get('id'); const draw = posts => { const post = posts.find(p => p.id === id); if (!post) { article.querySelector('.eyebrow').textContent = 'POST'; article.querySelector('h1').textContent = '게시글을 찾을 수 없습니다.'; article.querySelector('.article-meta').textContent = ''; article.querySelector('.article-body').textContent = ''; return; } article.querySelector('.eyebrow').textContent = `${post.category} · ${formatDate(post.date)}`; article.querySelector('h1').textContent = post.title; article.querySelector('.article-meta').textContent = `김윤자 · ${formatDate(post.date)}`; article.querySelector('.article-body').textContent = post.content; }; draw(cachedPosts()); syncPosts().then(draw); }
document.querySelectorAll('form:not(.auth-card form):not(.editor-wrap form)').forEach(form => form.addEventListener('submit', e => { e.preventDefault(); const message = form.querySelector('.form-message'); if (message) message.textContent = form.dataset.message || '처리되었습니다.'; }));
setupAuthNavigation(); setupAuthForm(); setupHomePosts(); setupPostList(); setupProfilePosts(); setupWriteForm(); setupDetail();
